version: "3.7"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
#      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./containers/proxy/vhost.d:/etc/nginx/vhost.d:rw
    networks:
      - nginx-proxy
      - default
    environment:
      DHPARAM_GENERATION: null
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - ./containers/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: default
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
#  nginx:
#    container_name: api_nginx
#    image: modelfak23/shop-nginx
#    environment:
#      - VIRTUAL_HOST=${NGINX_HOST}
#      - LETSENCRYPT_HOST=${NGINX_HOST}
#    volumes:
#      - ./.logs/nginx:/var/log/nginx
#      - ./app-php:/var/www/html
#      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./containers/nginx/sites/:/etc/nginx/sites-available
#      - ./containers/nginx/conf.d/:/etc/nginx/conf.d
##    ports:
##      - 80:80
##      - 443:443
#    expose:
#      - 80
#      - 443
#    depends_on:
#      - web
#    networks:
#      - default
#      - nginx-proxy
#  db:
#    image: modelfak23/shop-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root_mysql
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - db:/var/lib/mysql:rw
#    networks:
#      - default
#  web:
#    image: modelfak23/shop-php
#    volumes:
#      - ./app-php:/var/www/html
#    environment:
#      DB_PASSWORD: ${MYSQL_PASSWORD}
#      DB_HOST: ${MYSQL_HOST}
#      DB_USER: ${MYSQL_USER}
#      DB_NAME: ${MYSQL_DATABASE}
#    depends_on:
#      - db
#    expose:
#      - 9000
#    networks:
#      - default
networks:
  nginx-proxy:
    external: true    
volumes:
  db:
  conf:
  vhost:
  html:
  dhparam:
  certs:
    
